---
title: "R Notebook"
output:
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,dev = 'jpeg')
suppressMessages(library(knitr))
suppressMessages(library(dplyr))
```

## De-novo variants

Analysis of de-novo variants from 93 child-parents trios

```{r, echo=F}
t<-read.table('denovo_consequences_per_sample.tsv', stringsAsFactors = T)
colnames(t)<-c('sample', 'conseq','impact','symbol')
t['coding'] = t$impact!='MODIFIER'
```

### Impact of the variants

Genic variants fall into LOW, MODERATE, and HIGH categories

```{r, echo=F}
kable(t %>% count(impact))
```


Counts per sample

```{r impact.per.sample, echo=F}
kable(t %>% count(sample,impact, .drop=F) 
        %>% group_by(impact) 
        %>% summarize(mean=mean(n), min=min(n), max=max(n)))
```

### Consequence counts

```{r all.conseq, echo=F}
kable(t %>% count(conseq))
```
Consequences of exonic and splicing variants



```{r genic.conseq, echo=F}
kable(t[t$coding,] %>% count(conseq))
```


### Rare coding de-novo per-sample

```{r, coding.per.sample, echo=F}

kable(t[t$coding,] 
      %>% count(sample, .drop=F) 
      %>% summarize(mean=mean(n), min=min(n), max=max(n)))
```

Rare exonic denovo counts 
```{r, coding.per.sample.counts, echo=F}

kable(table((t[t$coding,] %>% count(sample, .drop=F))$n))
```


```{r coding.per.sample.hist, echo=F}
hist((t[t$coding,] %>% count(sample, .drop=F))$n, 
     main = '# rare de-novo exonic variants per sample',
     xlab = '# de-novo', ylab='# samples')
```



